trigger:
- main

parameters:
- name: subscription
  displayName: Select Azure Subscription
  type: string
  default: 'A'
  values:
    - 'A'
    - 'B'

- name: resourceGroup
  displayName: Select Resource Group
  type: string
  default: 'resourceGroup1'
  values:
    - 'resourceGroup1'
    - 'resourceGroup2'
    - 'resourceGroup3'
    - 'resourceGroup4'
    - 'resourceGroup5'

jobs:
- job: ValidateParameters
  displayName: 'Validate Parameters'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      echo "Selected Subscription: ${{ parameters.subscription }}"
      echo "Selected Resource Group: ${{ parameters.resourceGroup }}"

      if [ "${{ parameters.subscription }}" == "A" ]; then
        VALID_RESOURCE_GROUPS=("resourceGroup1" "resourceGroup2" "resourceGroup3")
      elif [ "${{ parameters.subscription }}" == "B" ]; then
        VALID_RESOURCE_GROUPS=("resourceGroup4" "resourceGroup5")
      else
        echo "Invalid subscription selected."
        exit 1
      fi

      if [[ " ${VALID_RESOURCE_GROUPS[@]} " =~ " ${{ parameters.resourceGroup }} " ]]; then
        echo "Selected resource group is valid for the chosen subscription."
      else
        echo "Selected resource group is NOT valid for the chosen subscription."
        exit 1
      fi
    displayName: 'Validate Selected Parameters'

- job: DeployPgBouncer
  displayName: 'Deploy pgBouncer'
  dependsOn: ValidateParameters
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      echo "Deploying pgBouncer to subscription: ${{ parameters.subscription }}"
      echo "Resource Group: ${{ parameters.resourceGroup }}"
    displayName: 'Echo Parameters'
  - task: AzureCLI@2
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Add your pgBouncer deployment script here
        echo "Deploying pgBouncer..."
        # Example: az deployment group create --resource-group ${{ parameters.resourceGroup }} --template-file your-template-file.json --parameters your-parameters
